export const machinesConfig = [
    {
    id: "PMC-01",
    model: "/models/machines/machine1.glb",
    position: [0, 1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Running",
  },
  {
    id: "PMC-02",
    model: "/models/machines/machine2.glb",
    position: [4, 1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Idle",
  },
  {
    id: "PMC-03",
    model: "/models/machines/machine3.glb",
    position: [8, 1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-04",
    model: "/models/machines/machine4.glb",
    position: [12, 1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-05",
    model: "/models/machines/machine5.glb",
    position: [16, 1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id:  "PMC-06",
    model: "/models/machines/machine6.glb",
    position: [16, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-07",
    model: "/models/machines/machine7.glb",
    position: [12, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-08",
    model: "/models/machines/machine8.glb",
    position: [8, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-09",
    model: "/models/machines/machine9.glb",
    position: [4, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-10",
    model: "/models/machines/machine10.glb",
    position: [0, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-11",
    model: "/models/machines/machine11.glb",
    position: [0, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-12",
    model: "/models/machines/machine12.glb",
    position: [4, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-13",
    model: "/models/machines/machine13.glb",
    position: [8, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-14",
    model: "/models/machines/machine14.glb",
    position: [12, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: "PMC-15",
    model: "/models/machines/machine15.glb",
    position: [16, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
];
