export const roadConfig = [
  {
    id: 1,
    texture: "./images/floor1.jpg",
    position: [5, 0, -10],
    rotation: [-Math.PI / 2, 0, 0],
    size: [30, 20],
    repeat: [3, 1],
  },
  {
    id: 2,
    texture: "./images/path1.jpeg",
    position: [6, 0.1, -2],
    rotation: [-Math.PI / 2, 0, 0],
    size: [25, 2],
    repeat: [3, 1],
  },
  {
    id: 3,
    texture: "./images/path1.jpeg",
    position: [6, 0.1, -9],
    rotation: [-Math.PI / 2, 0, 0],
    size: [25, 2],
    repeat: [3, 1],
  },
  {
    id: 4,
    texture: "./images/path1.jpeg",
    position: [6, 0.1, -15],
    rotation: [-Math.PI / 2, 0, 0],
    size: [25, 2],
    repeat: [3, 1],
  },
  {
    id: 5,
    texture: "images/path1.jpeg",
    position: [18, 0.1, -8.5],
    rotation: [-Math.PI / 2, 0, 1.55],
    size: [15, 1.5],
    repeat: [3, 1],
  },
  {
    id: 6,
    texture: "images/path1.jpeg",
    position: [-6, 0.1, -8.5],
    rotation: [-Math.PI / 2, 0, 1.55],
    size: [15, 1.5],
    repeat: [3, 1],
  },
];
