export const machinesConfig = [
  {
    id: 1,
    model: "/models/machines/machine1.glb",
    position: [0,1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Running",
  },
  {
    id: 2,
    model: "/models/machines/machine2.glb",
    position: [4, 1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Idle",
  },
  {
    id: 3,
    model: "/models/machines/machine3.glb",
    position: [8, 1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 4,
    model: "/models/machines/machine4.glb",
    position: [12, 1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 5,
    model: "/models/machines/machine5.glb",
    position: [16, 1.3, -17],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 6,
    model: "/models/machines/machine6.glb",
    position: [16, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 7,
    model: "/models/machines/machine7.glb",
    position: [12, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 8,
    model: "/models/machines/machine8.glb",
    position: [8, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 9,
    model: "/models/machines/machine9.glb",
    position: [4, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 10,
    model: "/models/machines/machine10.glb",
    position: [0, 1.3, -12],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 11,
    model: "/models/machines/machine11.glb",
    position: [0, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 12,
    model: "/models/machines/machine12.glb",
    position: [4, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 13,
    model: "/models/machines/machine13.glb",
    position: [8, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 14,
    model: "/models/machines/machine14.glb",
    position: [12, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
  {
    id: 15,
    model: "/models/machines/machine15.glb",
    position: [16, 1.3, -5],
    rotation: [0, 0, 0],
    scale: 0.006,
    status: "Stopped",
  },
];
